on:
  push:
    branches:
      - main

env:
  NX_CLOUD_ENCRYPTION_KEY: ${{ secrets.NX_CLOUD_ENCRYPTION_KEY }}
  NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
  NX_VERBOSE_LOGGING: ${{ secrets.NX_VERBOSE_LOGGING }}
  NX_SKIP_NX_CACHE: ${{ secrets.NX_SKIP_NX_CACHE }}
  NX_TASKS_RUNNER: ${{ secrets.NX_TASKS_RUNNER }}
  NX_PERF_LOGGING: ${{ secrets.NX_PERF_LOGGING }}

permissions:
  contents: write
  actions: read
  pull-requests: read
  id-token: write

jobs:
  build-test-lint:
    uses: ./.github/workflows/build-test-lint.yml
    secrets: inherit
    with:
      skip: lint

  release:
    runs-on: ubuntu-latest
    needs:
      - build-test-lint
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup
        id: setup
        uses: ./.github/actions/setup

      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - run: pnpm nx affected -t release --parallel=1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          LEFTHOOK: 0
